filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /usr/src/app/logs/*.log 
      - /usr/src/app/waste-logs/*.log
    json.message_key: message
    json.add_error_key: true

output.logstash:
  hosts: ["logstash:5044"]
